---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubemroperator
  labels:
    k8s-app: kubemroperator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kubemroperator
    spec:
      containers:
      - name: operator
        image: turbobytes/kubemr-operator
        command:
        - operator
        args:
        - --bucketname=$(KUBEMR_S3_BUCKET_NAME)
        - --bucketprefix=$(KUBEMR_S3_PREFIX)
        - --s3region=$(KUBEMR_S3_REGION)
        env:
          - name: KUBEMR_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: kubemr-operator
                key: s3-access
          - name: KUBEMR_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: kubemr-operator
                key: s3-secret
          - name: KUBEMR_S3_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: kubemr-operator
                key: s3_bucket
          - name: KUBEMR_S3_REGION
            valueFrom:
              configMapKeyRef:
                name: kubemr-operator
                key: s3_region
          - name: KUBEMR_S3_PREFIX
            valueFrom:
              configMapKeyRef:
                name: kubemr-operator
                key: s3_prefix
