apiVersion: "turbobytes.com/v1alpha1"
kind: MapReduceJob
metadata:
  #name: validobj1
  generateName: test-
spec:
  image: turbobytes/kubemr-wordcount
  replicas: 10
  inputs:
  - https://tools.ietf.org/rfc/rfc4501.txt
  - https://tools.ietf.org/rfc/rfc2017.txt
  - https://tools.ietf.org/rfc/rfc2425.txt
  template:
    spec:
      volumes:
      - name: tmpdir
        emptyDir: {}
      containers:
      - name: kubemrworker
        image: turbobytes/kubemr-wordcount
        volumeMounts:
        - name: tmpdir
          mountPath: /tmp
