apiVersion: v1
kind: Pod
metadata:
  name: wordcount
spec:
  containers:
  - name: kubemrworker
    image: turbobytes/kubemr-wordcountexec
    imagePullPolicy: Always
    env:
      - name: KUBEMR_S3_REGION
        value: ap-southeast-1
      - name: KUBEMR_S3_BUCKET_NAME
        value: kubemr
      - name: KUBEMR_S3_BUCKET_PREFIX
        value: test/
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  restartPolicy: Never
